### ISSUE TITLE
Make installation easier

### ISSUE THREAD

**Issue by gmelodie** [LTKills/heroes_builds_cheatsheet#5]
As it is now the user has to install python, pyqt5 AND heroes_build_scrapper before being able to use HBC. Make it so this installation is automatic

**Comment by gmelodie** [comment]
Actually I believe the installation is already easy (no need to install anything), but check that :)

**Comment by gmelodie** [comment]
As of HBC 1.1 it seems to be actually harder (lol) to run the program. Not really sure why is that. I'm currently using pyinstaller to generate the exe file

**Comment by ghost** [comment]
1.1 exe seems to be fine for me, are you running it on a computer without Python or the required packages? Pyinstaller seems to have issues bundling dependencies, so you may have to use cx_freeze.

**Comment by gmelodie** [comment]
I updated it last night, turns out the first version was not being built on one file only. Let us close this :smile:
